name: Sync VHS CSV

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:      # allow manual run

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download CSV
        run: curl -L "https://oakleytapes.com/vhs_transfers.csv" -o vhs_transfers.csv

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add vhs_transfers.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update VHS CSV"
          git push
